trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/deployment_samples/EdgeDataStore/Install'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/deployment_samples/EdgeDataStore/Install'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/deployment_samples/EdgeDataStore/Install'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.eds_azure.ini
  - name: InstallFile
    value: loc.ini
  - name: InstallFileLibrary
    value: product-readiness.eds_loc.ini
  - name: analysisProject
    value: EDS_Deployment_Install

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(InstallFile)
          fileLibrary: $(InstallFileLibrary)
          filePath: $(projPath)

      - task: CopyFiles@2
        inputs:
          sourceFolder: 'C:\eds-install-kit\'
          contents: 'EdgeDataStore.deb'
          targetFolder: '$(Build.SourcesDirectory)$(projPath)/templates/installation_files'
        displayName: 'Copy install kit'

      - bash: |
          chmod +x test.sh
          chmod +x remote.sh
          chmod +x reset.sh
          chmod +x reset-device.sh
          ./test.sh
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: powershell
